version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: aether-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: aether-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  master-node:
    image: python:3.11-slim
    container_name: aether-master-node
    command: ["sleep", "infinity"]
    volumes:
      - ../:/shared-repo

  vm-1:
    image: python:3.11-slim
    container_name: aether-vm-1
    command: ["sleep", "infinity"]

  vm-2:
    image: python:3.11-slim
    container_name: aether-vm-2
    command: ["sleep", "infinity"]

  nginx:
    image: nginx:1.27
    container_name: aether-nginx
    depends_on:
      - kafka
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  postgres:
    image: postgres:16-alpine
    container_name: aether-postgres
    environment:
      POSTGRES_USER: aether
      POSTGRES_PASSWORD: aether_pass
      POSTGRES_DB: aetherdb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aether"]
      interval: 10s
      timeout: 5s
      retries: 5
