events {}

http {
  upstream gateway_upstream {
    server host.docker.internal:8000;
  }

  upstream user_management_upstream {
    server host.docker.internal:8001;
  }

  upstream app_validator_upstream {
    server host.docker.internal:8011;
  }

  upstream app_registry_upstream {
    server host.docker.internal:8012;
  }

  upstream vm_health_upstream {
    server host.docker.internal:8013;
  }

  upstream app_deployer_upstream {
    server host.docker.internal:8014;
  }

  upstream app_health_upstream {
    server host.docker.internal:8015;
  }

  upstream lifecycle_upstream {
    server host.docker.internal:8016;
  }

  upstream notification_upstream {
    server host.docker.internal:8019;
  }

  server {
    listen 80;
    client_max_body_size 200m;

    location /v1/ {
      proxy_pass http://gateway_upstream;
    }

    location /login { proxy_pass http://user_management_upstream; }
    location /register { proxy_pass http://user_management_upstream; }
    location /me { proxy_pass http://user_management_upstream; }
    location /api-keys { proxy_pass http://user_management_upstream; }

    location /validate { proxy_pass http://app_validator_upstream; }
    location /registry/ { proxy_pass http://app_registry_upstream/; }
    location /vm-health/ { proxy_pass http://vm_health_upstream/; }
    location /deployer/ { proxy_pass http://app_deployer_upstream/; }
    location /app-health/ { proxy_pass http://app_health_upstream/; }
    location /lifecycle/ { proxy_pass http://lifecycle_upstream/; }
    location /notify/ { proxy_pass http://notification_upstream/; }

    location / {
      proxy_pass http://gateway_upstream;
    }
  }
}
